baseURL = "https://countdigi.github.io"

languageCode = "en-us"


pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsOptions    = "linenos=table"

[permalinks]
  posts = "/:year/:month/:slug/"

[taxonomies]
  tag = ""
  group = ""
  category = ""

[params]
  author = "Kevin M. Counts"
  title = "Kevin M. Counts"
  title_2 = "Linux, Bioinformatics, Distributed Systems Engineer"
